package com.application.myapplication.network

data class DataClass(

    var id :String,
    var title :String,
    var description :String,
    var datetime: Long,
    var cover :String,
    var cover_width : Int,
    var cover_height :Int,
    var account_url :String,
    var account_id:Long,
    var privacy :String,
    var layout :String,
    var views : Int,
    var link :String,
    var ups :Int,
    var downs:Int,
    var points:Int,
    var score:Int,
    var is_album :Boolean,
    var vote :String,
    var favorite:Boolean,
    var nsfw :Boolean,
    var section: String,
    var comment_count :Int,
    var favorite_count :Int,
    var topic:String,
    var topic_id:Int,
    var images_count: Int,
    var in_gallery :Boolean,
    var is_ad :Boolean,
    val tags :ArrayList<TagClass>,
    var ad_type:Int,
    var ad_url:String,
    var in_most_viral :Boolean,
    var include_album_ads:Boolean,
    var images : ArrayList<ImagesClass>,
    var ad_config: AdConfig
)